version: "3"


services:

  mysql-service:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=meuBanco
    ports:
      - "3318:3306"
    volumes:
      - db-teste:/var/lib/mysql

volumes:
  db-teste:
    driver: local
